function bm = getMask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 17-Dec-2015
%------------------------------------------------------


% Convert RGB image to chosen color space
I = RGB;

% Define thresholds for channel 1 based on histogram settings
channel1Min = 102.000;
channel1Max = 149.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 86.000;
channel2Max = 105.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 29.000;
channel3Max = 55.000;

% Create mask based on chosen histogram thresholds
C1Mask = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max);
C2Mask = C1Mask & (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max);
C3Mask = C2Mask & (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

bClosed = dip_array(label(closing(C3Mask,17,'elliptic'),Inf,0,0));
objectID = mode(bClosed(bClosed>0));
bm = bClosed == objectID;

